In [1]:
import torch
import torch.nn.functional as F

In [2]:
z1 = torch.randn(3, 5)
z2 = torch.randn(3, 5)

z1_n0 = F.normalize(z1, dim=0)
z2_n0 = F.normalize(z2, dim=0)

z1_n1 = F.normalize(z1, dim=1)
z2_n1 = F.normalize(z2, dim=1)

print(z1)
print(z1_n0)
print(z1_n1)

tensor([[ 0.5772,  0.2513, -0.3553, -1.5545, -1.2311],
        [-0.3176,  0.3088,  0.9342,  0.1271,  1.2219],
        [ 0.0751,  0.1495, -0.1637,  1.5167,  0.3560]])
tensor([[ 0.8705,  0.5908, -0.3508, -0.7145, -0.6953],
        [-0.4790,  0.7262,  0.9224,  0.0584,  0.6901],
        [ 0.1132,  0.3516, -0.1616,  0.6972,  0.2010]])
tensor([[ 0.2735,  0.1190, -0.1684, -0.7365, -0.5833],
        [-0.1978,  0.1923,  0.5818,  0.0792,  0.7610],
        [ 0.0476,  0.0949, -0.1039,  0.9627,  0.2259]])


In [3]:
print(z1.T @ z2)
print(z1_n0.T @ z2_n0)
print(z1_n1.T @ z2_n1)

c = z1_n1.T @ z2_n1 / 3

tensor([[ 1.3124,  0.3491, -0.2988, -0.3039,  0.3063],
        [ 0.5515,  0.1807, -0.7937,  0.8049,  0.2579],
        [-0.8819,  0.0375, -0.5313,  1.9285, -0.4525],
        [-3.2469, -2.2466, -0.4573, -1.8947,  1.8600],
        [-2.7729, -0.9561, -0.6295,  1.5571,  0.0638]])
tensor([[ 0.8922,  0.4877, -0.2295, -0.1852,  0.2998],
        [ 0.5847,  0.3937, -0.9503,  0.7648,  0.3936],
        [-0.3925,  0.0343, -0.2671,  0.7695, -0.2899],
        [-0.6729, -0.9567, -0.1070, -0.3520,  0.5548],
        [-0.7060, -0.5002, -0.1810,  0.3554,  0.0234]])
tensor([[ 0.2334,  0.0503, -0.0383, -0.1078,  0.0699],
        [ 0.0976,  0.0250, -0.1858,  0.1778,  0.0698],
        [-0.1625,  0.0345, -0.1433,  0.4945, -0.1164],
        [-0.5469, -0.5119, -0.3123, -0.4257,  0.5992],
        [-0.4880, -0.1763, -0.2594,  0.4349,  0.0657]])


In [18]:
def off_diagonal(x):
    # return a flattened view of the off-diagonal elements of a square matrix
    n, m = x.shape
    assert n == m
    return x.flatten()[:-1].view(n - 1, n + 1)[:, 1:].flatten()

In [22]:
invariance = torch.diagonal(c).add_(-1).pow_(2).sum()
redundancy_reduction = off_diagonal(c).pow_(2).sum()
loss = invariance + redundancy_reduction
print(loss)

tensor(6.5079)


In [4]:
print(c)
c.div_(2)
print(c)

tensor([[ 0.0778,  0.0168, -0.0128, -0.0359,  0.0233],
        [ 0.0325,  0.0083, -0.0619,  0.0593,  0.0233],
        [-0.0542,  0.0115, -0.0478,  0.1648, -0.0388],
        [-0.1823, -0.1706, -0.1041, -0.1419,  0.1997],
        [-0.1627, -0.0588, -0.0865,  0.1450,  0.0219]])
tensor([[ 0.0389,  0.0084, -0.0064, -0.0180,  0.0116],
        [ 0.0163,  0.0042, -0.0310,  0.0296,  0.0116],
        [-0.0271,  0.0058, -0.0239,  0.0824, -0.0194],
        [-0.0912, -0.0853, -0.0520, -0.0710,  0.0999],
        [-0.0813, -0.0294, -0.0432,  0.0725,  0.0109]])


### Export model

In [4]:
import torch
from nets import SiameseNetSync
from torchvision.models import resnet18

In [5]:
input_data = torch.rand(1,3,32,32)
model = SiameseNetSync(resnet18())
model(input_data)

TypeError: forward() missing 1 required positional argument: 'x2'

In [2]:
input_tensor = torch.rand((1, 1, 128, 128), dtype=torch.float32)

model = MyModel()

torch.onnx.export(
    model,                  # model to export
    (input_tensor,),        # inputs of the model,
    "my_model.onnx",        # filename of the ONNX model
    input_names=["input"],  # Rename inputs for the ONNX model
    dynamo=True             # True or False to select the exporter to use
)

c:\Users\Utente\anaconda3\envs\torch-wb2\lib\site-packages\onnxscript\converter.py:820: FutureWarning: 'onnxscript.values.Op.param_schemas' is deprecated in version 0.1 and will be removed in the future. Please use '.op_signature' instead.
  param_schemas = callee.param_schemas()
c:\Users\Utente\anaconda3\envs\torch-wb2\lib\site-packages\onnxscript\converter.py:820: FutureWarning: 'onnxscript.values.OnnxFunction.param_schemas' is deprecated in version 0.1 and will be removed in the future. Please use '.op_signature' instead.
  param_schemas = callee.param_schemas()


[torch.onnx] Obtain model graph for `MyModel([...]` with `torch.export.export`...
[torch.onnx] Obtain model graph for `MyModel([...]` with `torch.export.export`... ✅
[torch.onnx] Translate the graph into ONNX...
[torch.onnx] Translate the graph into ONNX... ✅


ONNXProgram(
    model=
        <
            ir_version=9,
            opset_imports={'': 18, 'pkg.onnxscript.torch_lib.common': 1},
            producer_name='pytorch',
            producer_version='2.5.1',
            domain=None,
            model_version=None,
        >
        graph(
            name=main_graph,
            inputs=(
                %"input"<FLOAT,[1,1,128,128]>
            ),
            outputs=(
                %"relu"<FLOAT,[1,128,124,124]>
            ),
            initializers=(
                %"conv1.weight"<FLOAT,[128,1,5,5]>,
                %"conv1.bias"<FLOAT,[128]>
            ),
        ) {
            0 |  # node_Conv_0
                 %"convolution"<FLOAT,[1,128,124,124]> ⬅️ ::Conv(%"input", %"conv1.weight", %"conv1.bias") {auto_pad=NOTSET, dilations=[1, 1], group=1, pads=[0, 0, 0, 0], strides=[1, 1]}
            1 |  # node_Relu_1
                 %"relu"<FLOAT,[1,128,124,124]> ⬅️ ::Relu(%"convolution")
            return %"relu"<FLOAT,[1,128,12

## Visualize network

In [1]:
import torch
import torch.nn as nn
from nets import visualize, SimpleNet, Block, SiameseNetSync as SiameseNet
from barlow import BarlowTwins

In [52]:
class Block(nn.Module):
    def __init__(self, in_channels, num_filters, kernel_size):
        super().__init__()
        self.layers = nn.Sequential(
            # prima convoluzione
            nn.Conv2d(in_channels=in_channels,
                      out_channels=num_filters,
                      kernel_size=kernel_size,
                      padding='same'),
            nn.BatchNorm2d(num_filters),
            nn.ReLU(),
            # seconda convoluzione in cui la dimensione del tensore resta invariata
            # quello che cambia (immagino) sono i valori dei pixel della feature map
            # nn.Conv2d(in_channels=num_filters,
            #           out_channels=num_filters,
            #           kernel_size=kernel_size,
            #           padding='same'),
            # nn.BatchNorm2d(num_filters),
            # nn.ReLU(),
            # dimezza la feature map per il blocco successivo
            nn.MaxPool2d(kernel_size=(2, 2)),
        )

    def forward(self, x):
        return self.layers(x)

In [ ]:
class SimpleNet(nn.Module):
    def __init__(self, num_filters, mlp_size, num_classes):
        super().__init__()
        # convolutional blocks
        self.blocks = nn.Sequential(
            Block(3, num_filters, (3,3)),
            Block(num_filters, num_filters*2, (3,3)),
            # Block(num_filters*2, num_filters*4, (3,3)),
            # Block(num_filters*4, num_filters*8, (3,3)),
        )
        # reduce convolution filters
        self.bottleneck = nn.Conv2d(
            in_channels=num_filters*2,
            out_channels=num_filters,
            kernel_size=(1,1)
        )
        # flatten convolution output
        self.flatten = nn.Flatten()  # Unroll the last feature map into a vector
        # mlp head
        self.mlp = nn.Sequential(
            nn.Linear(in_features=8*8*num_filters, out_features=2*mlp_size),
            nn.ReLU(),
            nn.Linear(in_features=2*mlp_size, out_features=mlp_size),
            nn.ReLU()
        )
        self.fc = nn.Linear(in_features=mlp_size, out_features=num_classes)

    def forward(self, x):
        h = x
        # convolution
        h = self.blocks(h)
        # reduce channels
        h = self.bottleneck(h)
        # flatten
        # print(h.shape)
        h = self.flatten(h)
        # go to classification head
        h = self.mlp(h)
        h = self.fc(h)  # logits
        return h

In [79]:
z_dim = 128
backbone = SimpleNet(16, z_dim, 10)
model = SiameseNet(backbone)
criterion = BarlowTwins(0.005, z_dim)

input_data = torch.randn(64, 3, 32, 32)

In [80]:
outputs = backbone(input_data)
outputs.shape

torch.Size([64, 16, 8, 8])


torch.Size([64, 128])

In [81]:
outputs = model(input_data, input_data)
features1, features2 = outputs.values()
loss = criterion(features1, features2)
print(loss.item())

torch.Size([128, 16, 8, 8])
1984.684326171875


In [82]:
input_repr = torch.randn(64, z_dim)
outputs = criterion.projector(input_repr)
print(outputs.shape)
outputs = criterion.bn(outputs)
print(outputs.shape)

torch.Size([64, 2048])
torch.Size([64, 2048])


In [83]:
visualize(backbone, input_data)

torch.Size([64, 16, 8, 8])


Computed output, shape=torch.Size([64, 128])

torch.Size([64, 16, 8, 8])


==============================================================================================
Layer (type (var_name))                  Input Shape        Output Shape       Param #
==============================================================================================
SimpleNet (SimpleNet)                    [64, 3, 32, 32]    [64, 128]          --
├─Sequential (blocks)                    [64, 3, 32, 32]    [64, 32, 8, 8]     --
│    └─Block (0)                         [64, 3, 32, 32]    [64, 16, 16, 16]   --
│    │    └─Sequential (layers)          [64, 3, 32, 32]    [64, 16, 16, 16]   --
│    │    │    └─Conv2d (0)              [64, 3, 32, 32]    [64, 16, 32, 32]   448
│    │    │    └─BatchNorm2d (1)         [64, 16, 32, 32]   [64, 16, 32, 32]   32
│    │    │    └─ReLU (2)                [64, 16, 32, 32]   [64, 16, 32, 32]   --
│    │    │    └─MaxPool2d (3)           [64, 16, 32, 32]   [64, 16, 16, 16]   --
│    └─Block (1)                         [64, 16, 16, 16]   [64, 32, 8, 8]     --
│    │    └─Sequential (layers)          [64, 16, 16, 16]   [64, 32, 8, 8]     --
│    │    │    └─Conv2d (0)              [64, 16, 16, 16]   [64, 32, 16, 16]   4,640
│    │    │    └─BatchNorm2d (1)         [64, 32, 16, 16]   [64, 32, 16, 16]   64
│    │    │    └─ReLU (2)                [64, 32, 16, 16]   [64, 32, 16, 16]   --
│    │    │    └─MaxPool2d (3)           [64, 32, 16, 16]   [64, 32, 8, 8]     --
├─Conv2d (bottleneck)                    [64, 32, 8, 8]     [64, 16, 8, 8]     528
├─Flatten (flatten)                      [64, 16, 8, 8]     [64, 1024]         --
├─Sequential (mlp)                       [64, 1024]         [64, 128]          --
│    └─Linear (0)                        [64, 1024]         [64, 256]          262,400
│    └─ReLU (1)                          [64, 256]          [64, 256]          --
│    └─Linear (2)                        [64, 256]          [64, 128]          32,896
│    └─ReLU (3)                          [64, 128]          [64, 128]          --
├─Identity (fc)                          [64, 128]          [64, 128]          --
==============================================================================================
Total params: 301,008
Trainable params: 301,008
Non-trainable params: 0
Total mult-adds (M): 126.45
==============================================================================================
Input size (MB): 0.79
Forward/backward pass size (MB): 25.89
Params size (MB): 1.20
Estimated Total Size (MB): 27.88
==============================================================================================

In [15]:
from torchvision.models import resnet18
resnet = resnet18()
visualize(resnet, input_data)

Computed output, shape=torch.Size([64, 1000])

==============================================================================================
Layer (type (var_name))                  Input Shape        Output Shape       Param #
==============================================================================================
ResNet (ResNet)                          [64, 3, 32, 32]    [64, 1000]         --
├─Conv2d (conv1)                         [64, 3, 32, 32]    [64, 64, 16, 16]   9,408
├─BatchNorm2d (bn1)                      [64, 64, 16, 16]   [64, 64, 16, 16]   128
├─ReLU (relu)                            [64, 64, 16, 16]   [64, 64, 16, 16]   --
├─MaxPool2d (maxpool)                    [64, 64, 16, 16]   [64, 64, 8, 8]     --
├─Sequential (layer1)                    [64, 64, 8, 8]     [64, 64, 8, 8]     --
│    └─BasicBlock (0)                    [64, 64, 8, 8]     [64, 64, 8, 8]     --
│    │    └─Conv2d (conv1)               [64, 64, 8, 8]     [64, 64, 8, 8]     36,864
│    │    └─BatchNorm2d (bn1)            [64, 64, 8, 8]     [64, 64, 8, 8]     128
│    │    └─ReLU (relu)                  [64, 64, 8, 8]     [64, 64, 8, 8]     --
│    │    └─Conv2d (conv2)               [64, 64, 8, 8]     [64, 64, 8, 8]     36,864
│    │    └─BatchNorm2d (bn2)            [64, 64, 8, 8]     [64, 64, 8, 8]     128
│    │    └─ReLU (relu)                  [64, 64, 8, 8]     [64, 64, 8, 8]     --
│    └─BasicBlock (1)                    [64, 64, 8, 8]     [64, 64, 8, 8]     --
│    │    └─Conv2d (conv1)               [64, 64, 8, 8]     [64, 64, 8, 8]     36,864
│    │    └─BatchNorm2d (bn1)            [64, 64, 8, 8]     [64, 64, 8, 8]     128
│    │    └─ReLU (relu)                  [64, 64, 8, 8]     [64, 64, 8, 8]     --
│    │    └─Conv2d (conv2)               [64, 64, 8, 8]     [64, 64, 8, 8]     36,864
│    │    └─BatchNorm2d (bn2)            [64, 64, 8, 8]     [64, 64, 8, 8]     128
│    │    └─ReLU (relu)                  [64, 64, 8, 8]     [64, 64, 8, 8]     --
├─Sequential (layer2)                    [64, 64, 8, 8]     [64, 128, 4, 4]    --
│    └─BasicBlock (0)                    [64, 64, 8, 8]     [64, 128, 4, 4]    --
│    │    └─Conv2d (conv1)               [64, 64, 8, 8]     [64, 128, 4, 4]    73,728
│    │    └─BatchNorm2d (bn1)            [64, 128, 4, 4]    [64, 128, 4, 4]    256
│    │    └─ReLU (relu)                  [64, 128, 4, 4]    [64, 128, 4, 4]    --
│    │    └─Conv2d (conv2)               [64, 128, 4, 4]    [64, 128, 4, 4]    147,456
│    │    └─BatchNorm2d (bn2)            [64, 128, 4, 4]    [64, 128, 4, 4]    256
│    │    └─Sequential (downsample)      [64, 64, 8, 8]     [64, 128, 4, 4]    --
│    │    │    └─Conv2d (0)              [64, 64, 8, 8]     [64, 128, 4, 4]    8,192
│    │    │    └─BatchNorm2d (1)         [64, 128, 4, 4]    [64, 128, 4, 4]    256
│    │    └─ReLU (relu)                  [64, 128, 4, 4]    [64, 128, 4, 4]    --
│    └─BasicBlock (1)                    [64, 128, 4, 4]    [64, 128, 4, 4]    --
│    │    └─Conv2d (conv1)               [64, 128, 4, 4]    [64, 128, 4, 4]    147,456
│    │    └─BatchNorm2d (bn1)            [64, 128, 4, 4]    [64, 128, 4, 4]    256
│    │    └─ReLU (relu)                  [64, 128, 4, 4]    [64, 128, 4, 4]    --
│    │    └─Conv2d (conv2)               [64, 128, 4, 4]    [64, 128, 4, 4]    147,456
│    │    └─BatchNorm2d (bn2)            [64, 128, 4, 4]    [64, 128, 4, 4]    256
│    │    └─ReLU (relu)                  [64, 128, 4, 4]    [64, 128, 4, 4]    --
├─Sequential (layer3)                    [64, 128, 4, 4]    [64, 256, 2, 2]    --
│    └─BasicBlock (0)                    [64, 128, 4, 4]    [64, 256, 2, 2]    --
│    │    └─Conv2d (conv1)               [64, 128, 4, 4]    [64, 256, 2, 2]    294,912
│    │    └─BatchNorm2d (bn1)            [64, 256, 2, 2]    [64, 256, 2, 2]    512
│    │    └─ReLU (relu)                  [64, 256, 2, 2]    [64, 256, 2, 2]    --
│    │    └─Conv2d (conv2)               [64, 256, 2, 2]    [64, 256, 2, 2]    589,824
│    │    └─BatchNorm2d (bn2)            [64, 256, 2,

## Loading data

In [1]:
import time
from dataset import AugmentedImageDataset, BaseDataset, MakeDataLoaders
from torch.utils.data import DataLoader
from tqdm import tqdm
from types import SimpleNamespace
workers = [0, 1, 2, 4, 6, 8]

Load data for pre-training (with augmentation)

In [ ]:
trainset = AugmentedImageDataset()
aug_data = {}

In [ ]:
for w in workers:
    ## Load data
    config = SimpleNamespace(
        **dict(batch_size=64, val_size=0.1, num_workers=w, epochs=1))
    print("Workers:", config.num_workers)
    train_loader = DataLoader(
        trainset, batch_size=config.batch_size, shuffle=True,
        num_workers=config.num_workers, pin_memory=True)
    ## Training loop
    start = time.time()
    for epoch in range(1, config.epochs + 1):
        with tqdm(train_loader, unit="batch") as tepoch:
            for batch_idx, (view1, view2, _) in enumerate(tepoch):
                if batch_idx == 0:
                    time_to_start = time.time() - start
                    start = time.time()
                tepoch.set_description(f"Pre-train epoch: {epoch}")
                pass
    print(f"Time to start: {time_to_start:.2f}")
    time_to_process = time.time() - start
    print(f"Time to process: {time_to_process:.2f}")
    aug_data[f"Workers {config.num_workers}"] = [time_to_start, time_to_process]
    print()

Files already downloaded and verified
Workers: 0


Pre-train epoch: 1: 100%|██████████| 782/782 [02:08<00:00,  6.09batch/s]


Time to start: 1.44
Time to process: 126.97

Workers: 1


Pre-train epoch: 1: 100%|██████████| 782/782 [01:25<00:00,  9.16batch/s]


Time to start: 2.94
Time to process: 82.41

Workers: 2


Pre-train epoch: 1: 100%|██████████| 782/782 [00:48<00:00, 16.04batch/s]


Time to start: 5.60
Time to process: 43.14

Workers: 4


Pre-train epoch: 1: 100%|██████████| 782/782 [00:34<00:00, 22.49batch/s]


Time to start: 10.93
Time to process: 23.83

Workers: 6


Pre-train epoch: 1: 100%|██████████| 782/782 [00:37<00:00, 21.01batch/s]


Time to start: 16.63
Time to process: 20.59

Workers: 8


Pre-train epoch: 1: 100%|██████████| 782/782 [00:39<00:00, 19.91batch/s]

Time to start: 21.81
Time to process: 17.46



In [6]:
aug_data

{'Workers 0': [1.4438307285308838, 126.96957683563232],
 'Workers 1': [2.9401235580444336, 82.41152834892273],
 'Workers 2': [5.603337526321411, 43.13792157173157],
 'Workers 4': [10.932814359664917, 23.83292317390442],
 'Workers 6': [16.634984970092773, 20.591933965682983],
 'Workers 8': [21.81459140777588, 17.46005392074585]}

Load data for supervised learning training (no augmentation)

In [3]:
train_data = BaseDataset()
testset = BaseDataset(train=False)
base_data = {}  # {"n_workers": [time_to_start, time_to_process]}

Files already downloaded and verified
Files already downloaded and verified


In [5]:
for w in workers:
    ## Load data
    config = SimpleNamespace(
        **dict(batch_size=64, val_size=0.1, num_workers=w, epochs=1))
    print("Workers:", config.num_workers)
    loader = MakeDataLoaders(train_data, testset, config)
    train_loader = loader.train_loader
    ## Training loop
    start = time.time()
    for epoch in range(1, config.epochs + 1):
        with tqdm(train_loader, unit="batch") as tepoch:
            for batch_idx, (X, y) in enumerate(tepoch):
                if batch_idx == 0:
                    time_to_start = time.time() - start
                    start = time.time()
                tepoch.set_description(f"Pre-train epoch: {epoch}")
                pass
    print(f"Time to start: {time_to_start:.2f}")
    time_to_process = time.time() - start
    print(f"Time to process: {time_to_process:.2f}")
    base_data[f"Workers {config.num_workers}"] = [time_to_start, time_to_process]
    print()

Workers: 0


Pre-train epoch: 1: 100%|██████████| 704/704 [00:03<00:00, 202.17batch/s]


Time to start: 0.01
Time to process: 3.47

Workers: 1


Pre-train epoch: 1: 100%|██████████| 704/704 [00:05<00:00, 117.91batch/s]


Time to start: 2.74
Time to process: 3.24

Workers: 2


Pre-train epoch: 1: 100%|██████████| 704/704 [00:07<00:00, 94.73batch/s] 


Time to start: 5.42
Time to process: 2.01

Workers: 4


Pre-train epoch: 1: 100%|██████████| 704/704 [00:12<00:00, 54.62batch/s] 


Time to start: 11.20
Time to process: 1.69

Workers: 6


Pre-train epoch: 1: 100%|██████████| 704/704 [00:17<00:00, 39.84batch/s] 


Time to start: 15.99
Time to process: 1.68

Workers: 8


Pre-train epoch: 1: 100%|██████████| 704/704 [00:22<00:00, 30.92batch/s] 

Time to start: 20.94
Time to process: 1.83



In [6]:
base_data

{'Workers 0': [0.010998964309692383, 3.474064588546753],
 'Workers 1': [2.7367637157440186, 3.236891508102417],
 'Workers 2': [5.421192646026611, 2.01306414604187],
 'Workers 4': [11.200770139694214, 1.690000295639038],
 'Workers 6': [15.988219738006592, 1.6848559379577637],
 'Workers 8': [20.942496299743652, 1.8250188827514648]}